export const ITEM_LIST = [
  {
    name: document.querySelector(".cursorbtn"),
    value: 1,
    price: 10,
    divQuantity: document.querySelector(".num-cursor"),
    divRentability: document.querySelector(".num-cursor-waffles"),
    divPrice: document.querySelector(".priceC"),
  },
  {
    name: document.querySelector(".mpbtn"),
    value: 10,
    price: 100,
    divQuantity: document.querySelector(".num-manneken-pis"),
    divRentability: document.querySelector(".num-manneken-pis-waffles"),
    divPrice: document.querySelector(".priceMP"),
  },
  {
    name: document.querySelector(".jcvdbtn"),
    value: 25,
    price: 250,
    divQuantity: document.querySelector(".num-jean-claude"),
    divRentability: document.querySelector(".num-jean-waffles"),
    divPrice: document.querySelector(".priceJC"),
  },
  {
    name: document.querySelector(".bakerybtn"),
    value: 75,
    price: 750,
    divQuantity: document.querySelector(".num-bakery"),
    divRentability: document.querySelector(".num-bakery-waffles"),
    divPrice: document.querySelector(".priceB"),
  },
  {
    name: document.querySelector(".atombtn"),
    value: 150,
    price: 1500,
    divQuantity: document.querySelector(".num-atomium"),
    divRentability: document.querySelector(".num-atomium-waffles"),
    divPrice: document.querySelector(".priceA"),
  },
  {
    name: document.querySelector(".gpbtn"),
    value: 400,
    price: 4000,
    divQuantity: document.querySelector(".num-grand-place"),
    divRentability: document.querySelector(".num-grand-place-waffles"),
    divPrice: document.querySelector(".priceG"),
  },
];
export const ITEM_LIST_SELL = [
  {
    name: document.querySelector(".cursorbtnSELL"),
    quantity: 0,
    divQuantity: document.querySelector(".num-cursorSELL"),
    divRentability: document.querySelector(".num-cursor-wafflesSELL"),
    divPrice: document.querySelector(".priceCSELL"),
  },
  {
    name: document.querySelector(".mpbtnSELL"),
    quantity: 0,
    divQuantity: document.querySelector(".num-manneken-pisSELL"),
    divRentability: document.querySelector(".num-manneken-pis-wafflesSELL"),
    divPrice: document.querySelector(".priceMPSELL"),
  },
  {
    name: document.querySelector(".jcvdbtnSELL"),
    quantity: 0,
    divQuantity: document.querySelector(".num-jean-claudeSELL"),
    divRentability: document.querySelector(".num-jean-wafflesSELL"),
    divPrice: document.querySelector(".priceJCSELL"),
  },
  {
    name: document.querySelector(".bakerybtnSELL"),
    quantity: 0,
    divQuantity: document.querySelector(".num-bakerySELL"),
    divRentability: document.querySelector(".num-bakery-wafflesSELL"),
    divPrice: document.querySelector(".priceBSELL"),
  },
  {
    name: document.querySelector(".atombtnSELL"),
    quantity: 0,
    divQuantity: document.querySelector(".num-atomiumSELL"),
    divRentability: document.querySelector(".num-atomium-wafflesSELL"),
    divPrice: document.querySelector(".priceASELL"),
  },
  {
    name: document.querySelector(".gpbtnSELL"),
    quantity: 0,
    divQuantity: document.querySelector(".num-grand-placeSELL"),
    divRentability: document.querySelector(".num-grand-place-wafflesSELL"),
    divPrice: document.querySelector(".priceGSELL"),
  },
];
