const ITEM_LIST = [
  {
    name: document.querySelector("#cursor"),
    value: 1,
    price: 10,
    quantity: 0,
    divQuantity: document.querySelector("#num-cursor"),
    divRentability: document.querySelector("#num-cursor-waffles"),
    divPrice: document.querySelector(".priceC"),
  },
  {
    name: document.querySelector("#manneken-pis"),
    value: 10,
    price: 100,
    quantity: 0,
    divQuantity: document.querySelector("#num-manneken-pis"),
    divRentability: document.querySelector("#num-manneken-pis-waffles"),
    divPrice: document.querySelector(".priceMP"),
  },
  {
    name: document.querySelector("#jean-claude"),
    value: 25,
    price: 250,
    quantity: 0,
    divQuantity: document.querySelector("#num-jean-claude"),
    divRentability: document.querySelector("#num-jean-waffles"),
    divPrice: document.querySelector(".priceJC"),
  },
  {
    name: document.querySelector("#bakery"),
    value: 75,
    price: 750,
    quantity: 0,
    divQuantity: document.querySelector("#num-bakery"),
    divRentability: document.querySelector("#num-bakery-waffles"),
    divPrice: document.querySelector(".priceB"),
  },
  {
    name: document.querySelector("#atomium"),
    value: 150,
    price: 1500,
    quantity: 0,
    divQuantity: document.querySelector("#num-atomium"),
    divRentability: document.querySelector("#num-atomium-waffles"),
    divPrice: document.querySelector(".priceA"),
  },
  {
    name: document.querySelector("#grand-place"),
    value: 400,
    price: 4000,
    quantity: 0,
    divQuantity: document.querySelector("#num-grand-place"),
    divRentability: document.querySelector("#num-grand-place-waffles"),
    divPrice: document.querySelector(".priceG"),
  },
];
